### ISSUE TITLE
you have finished it?

### ISSUE THREAD

**Issue by cuiwei9567** [babyformula/LSD-SLAM-with-PerceptIn-stereo-camera#1]
Is't enough to get the better result as you show in the picture?

**Comment by babyformula** [comment]
Not yet. The framework has been presented in this git so far, based on the SDK of PerceptIn corp's inertial stereo cameras.

However, the algorithms of Depth estimation part and Map optimization part of stereo cameras' LSD-SLAM has made some progress. But augmentation and implementation of these modules and the Sophus lib is quite a huge project, almost equivalent to write a whole set of SLAM.

In fact, the ongoing work focusing on stereo cameras' LSD-SLAM will obviously improve the performance: 1) robust during camera's large-scale movement and rotation. 2)improving initialization time by given a priori stereo's depth estimation.

**Comment by babyformula** [comment]
P.S. The result shown in the picture could be achieved using current method of LSD-SLAM in this git , which has already been realized. And I'll sync the part of better initialization and robust improvement part once finished.

**Comment by vien123** [comment]
why there is no source code?How to build it ?

**Comment by babyformula** [comment]
@vien123 This project is based on [PerceptIn Corp](https://www.perceptin.io/)'s hardware, an inertial stereo camera module. And you can find the node publisher cpp code [here](https://raw.githubusercontent.com/babyformula/LSD-SLAM-with-PerceptIn-stereo-camera/master/ros_opencv/src/opencv_publisher/src/opencv_publisher_node.cpp), the method of building it in the [readme.md](https://github.com/babyformula/LSD-SLAM-with-PerceptIn-stereo-camera/blob/master/README.md)
